apiVersion: v1
kind: Namespace
metadata:
  name: netmska
  labels:
    name: netmska
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: net-test
  name: net-test
  namespace: netmska
spec:
  replicas: 5
  selector:
    matchLabels:
      app: net-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: net-test
    spec:
      containers:
      - image: alpine
        name: alpine
        command:
        - sleep
        - "3600"
        resources: {}
status: {}
